module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14140',
    id: 1881649602,
    node_id: 'I_kwDOCWUK8M5wJ7HC',
    number: 14140,
    title: 'Broken: RIK HD Cyprus',
    user: {
      login: 'ROBGagn',
      id: 124619576,
      node_id: 'U_kgDOB22LOA',
      avatar_url: 'https://avatars.githubusercontent.com/u/124619576?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ROBGagn',
      html_url: 'https://github.com/ROBGagn',
      followers_url: 'https://api.github.com/users/ROBGagn/followers',
      following_url: 'https://api.github.com/users/ROBGagn/following{/other_user}',
      gists_url: 'https://api.github.com/users/ROBGagn/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ROBGagn/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ROBGagn/subscriptions',
      organizations_url: 'https://api.github.com/users/ROBGagn/orgs',
      repos_url: 'https://api.github.com/users/ROBGagn/repos',
      events_url: 'https://api.github.com/users/ROBGagn/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ROBGagn/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 3241837512,
        node_id: 'MDU6TGFiZWwzMjQxODM3NTEy',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/CY',
        name: 'CY',
        color: '90FA7B',
        default: false,
        description: 'Cyprus'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-05T10:09:04Z',
    updated_at: '2023-09-07T00:50:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://l6.cloudskep.com/rikcy/rikhd/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\nhttp://l6.cloudskep.com/rikcy/rikhd/playlist2.m3u8\n\n### Notes (optional)\n\nToken needed...\r\nSame issue with RIK 1 and 2. May happen in the future with ANT1 Cyprus, Sigma and Omega.\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
