module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14151',
    id: 1884653836,
    node_id: 'I_kwDOCWUK8M5wVYkM',
    number: 14151,
    title: 'Remove: VTV',
    user: {
      login: 'kaikyoofers',
      id: 67206080,
      node_id: 'MDQ6VXNlcjY3MjA2MDgw',
      avatar_url: 'https://avatars.githubusercontent.com/u/67206080?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/kaikyoofers',
      html_url: 'https://github.com/kaikyoofers',
      followers_url: 'https://api.github.com/users/kaikyoofers/followers',
      following_url: 'https://api.github.com/users/kaikyoofers/following{/other_user}',
      gists_url: 'https://api.github.com/users/kaikyoofers/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/kaikyoofers/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/kaikyoofers/subscriptions',
      organizations_url: 'https://api.github.com/users/kaikyoofers/orgs',
      repos_url: 'https://api.github.com/users/kaikyoofers/repos',
      events_url: 'https://api.github.com/users/kaikyoofers/events{/privacy}',
      received_events_url: 'https://api.github.com/users/kaikyoofers/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 2043160604,
        node_id: 'MDU6TGFiZWwyMDQzMTYwNjA0',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/BR',
        name: 'BR',
        color: 'ccdcff',
        default: false,
        description: 'Brazil'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-06T19:51:43Z',
    updated_at: '2023-09-07T00:48:57Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Stream URL\n\nhttps://ythls.onrender.com/channel/UC40TUSUx490U5uR1lZt3Ajg.m3u8\n\n### Reason\n\nNot loading\n\n### Notes (optional)\n\nOne link (VTV.br) is misspelled.\n\n### Contributing Guide\n\n- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14151/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14140',
    id: 1881649602,
    node_id: 'I_kwDOCWUK8M5wJ7HC',
    number: 14140,
    title: 'Broken: RIK HD Cyprus',
    user: {
      login: 'ROBGagn',
      id: 124619576,
      node_id: 'U_kgDOB22LOA',
      avatar_url: 'https://avatars.githubusercontent.com/u/124619576?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ROBGagn',
      html_url: 'https://github.com/ROBGagn',
      followers_url: 'https://api.github.com/users/ROBGagn/followers',
      following_url: 'https://api.github.com/users/ROBGagn/following{/other_user}',
      gists_url: 'https://api.github.com/users/ROBGagn/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ROBGagn/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ROBGagn/subscriptions',
      organizations_url: 'https://api.github.com/users/ROBGagn/orgs',
      repos_url: 'https://api.github.com/users/ROBGagn/repos',
      events_url: 'https://api.github.com/users/ROBGagn/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ROBGagn/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 3241837512,
        node_id: 'MDU6TGFiZWwzMjQxODM3NTEy',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/CY',
        name: 'CY',
        color: '90FA7B',
        default: false,
        description: 'Cyprus'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:add',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-05T10:09:04Z',
    updated_at: '2023-09-07T00:50:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://l6.cloudskep.com/rikcy/rikhd/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\nhttp://l6.cloudskep.com/rikcy/rikhd/playlist2.m3u8\n\n### Notes (optional)\n\nToken needed...\r\nSame issue with RIK 1 and 2. May happen in the future with ANT1 Cyprus, Sigma and Omega.\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14140/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14139',
    id: 1881648047,
    node_id: 'I_kwDOCWUK8M5wJ6uv',
    number: 14139,
    title: 'Broken: RIK2 Cyprus',
    user: {
      login: 'ROBGagn',
      id: 124619576,
      node_id: 'U_kgDOB22LOA',
      avatar_url: 'https://avatars.githubusercontent.com/u/124619576?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ROBGagn',
      html_url: 'https://github.com/ROBGagn',
      followers_url: 'https://api.github.com/users/ROBGagn/followers',
      following_url: 'https://api.github.com/users/ROBGagn/following{/other_user}',
      gists_url: 'https://api.github.com/users/ROBGagn/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ROBGagn/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ROBGagn/subscriptions',
      organizations_url: 'https://api.github.com/users/ROBGagn/orgs',
      repos_url: 'https://api.github.com/users/ROBGagn/repos',
      events_url: 'https://api.github.com/users/ROBGagn/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ROBGagn/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 3241837512,
        node_id: 'MDU6TGFiZWwzMjQxODM3NTEy',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/CY',
        name: 'CY',
        color: '90FA7B',
        default: false,
        description: 'Cyprus'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-05T10:08:08Z',
    updated_at: '2023-09-07T00:50:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://l6.cloudskep.com/rikcy/rik2/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nToken needed...\r\nSame issue with RIK 1 and HD. May happen in the future with ANT1 Cyprus, Sigma and Omega.\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14139/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14138',
    id: 1881646342,
    node_id: 'I_kwDOCWUK8M5wJ6UG',
    number: 14138,
    title: 'Broken: RIK1 Cyprus',
    user: {
      login: 'ROBGagn',
      id: 124619576,
      node_id: 'U_kgDOB22LOA',
      avatar_url: 'https://avatars.githubusercontent.com/u/124619576?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ROBGagn',
      html_url: 'https://github.com/ROBGagn',
      followers_url: 'https://api.github.com/users/ROBGagn/followers',
      following_url: 'https://api.github.com/users/ROBGagn/following{/other_user}',
      gists_url: 'https://api.github.com/users/ROBGagn/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ROBGagn/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ROBGagn/subscriptions',
      organizations_url: 'https://api.github.com/users/ROBGagn/orgs',
      repos_url: 'https://api.github.com/users/ROBGagn/repos',
      events_url: 'https://api.github.com/users/ROBGagn/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ROBGagn/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 3241837512,
        node_id: 'MDU6TGFiZWwzMjQxODM3NTEy',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/CY',
        name: 'CY',
        color: '90FA7B',
        default: false,
        description: 'Cyprus'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-05T10:07:08Z',
    updated_at: '2023-09-07T00:50:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://l6.cloudskep.com/rikcy/rik1/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nToken needed...\r\nSame issue with RIK 2 and HD, Alpha TV Cyprus. May happen in the future with ANT1 Cyprus, Sigma and Omega.\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14138/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14137',
    id: 1881642924,
    node_id: 'I_kwDOCWUK8M5wJ5es',
    number: 14137,
    title: 'Broken: Alpha TV Cyprus',
    user: {
      login: 'ROBGagn',
      id: 124619576,
      node_id: 'U_kgDOB22LOA',
      avatar_url: 'https://avatars.githubusercontent.com/u/124619576?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ROBGagn',
      html_url: 'https://github.com/ROBGagn',
      followers_url: 'https://api.github.com/users/ROBGagn/followers',
      following_url: 'https://api.github.com/users/ROBGagn/following{/other_user}',
      gists_url: 'https://api.github.com/users/ROBGagn/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ROBGagn/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ROBGagn/subscriptions',
      organizations_url: 'https://api.github.com/users/ROBGagn/orgs',
      repos_url: 'https://api.github.com/users/ROBGagn/repos',
      events_url: 'https://api.github.com/users/ROBGagn/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ROBGagn/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 3241837512,
        node_id: 'MDU6TGFiZWwzMjQxODM3NTEy',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/CY',
        name: 'CY',
        color: '90FA7B',
        default: false,
        description: 'Cyprus'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-05T10:05:06Z',
    updated_at: '2023-09-07T00:50:05Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://l4.cloudskep.com/alphacyp/acy/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nToken now needed...\r\nSame issue with RIK 1, 2 and HD. May happen in the future with RIK Sat, ANT1 Cyprus, Sigma and Omega.\r\n\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14137/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14120',
    id: 1878180439,
    node_id: 'I_kwDOCWUK8M5v8sJX',
    number: 14120,
    title: 'Broken: Canal 5 (MX)',
    user: {
      login: 'chris202020202020',
      id: 141375812,
      node_id: 'U_kgDOCG05RA',
      avatar_url: 'https://avatars.githubusercontent.com/u/141375812?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/chris202020202020',
      html_url: 'https://github.com/chris202020202020',
      followers_url: 'https://api.github.com/users/chris202020202020/followers',
      following_url: 'https://api.github.com/users/chris202020202020/following{/other_user}',
      gists_url: 'https://api.github.com/users/chris202020202020/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/chris202020202020/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/chris202020202020/subscriptions',
      organizations_url: 'https://api.github.com/users/chris202020202020/orgs',
      repos_url: 'https://api.github.com/users/chris202020202020/repos',
      events_url: 'https://api.github.com/users/chris202020202020/events{/privacy}',
      received_events_url: 'https://api.github.com/users/chris202020202020/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 2980444955,
        node_id: 'MDU6TGFiZWwyOTgwNDQ0OTU1',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/MX',
        name: 'MX',
        color: '02A7D1',
        default: false,
        description: 'Mexico'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-01T23:49:28Z',
    updated_at: '2023-09-07T00:24:05Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://190.61.102.67:2000/play/a038/index.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nReplacement For A Broken Stream To A New Stream For Canal 5 (MX) Please\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14120/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14108',
    id: 1877534239,
    node_id: 'I_kwDOCWUK8M5v6OYf',
    number: 14108,
    title: 'Broken: SBS TBC (TBC 대구방송) (540p)',
    user: {
      login: 'AVGCFan1995',
      id: 143818591,
      node_id: 'U_kgDOCJJ_Xw',
      avatar_url: 'https://avatars.githubusercontent.com/u/143818591?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/AVGCFan1995',
      html_url: 'https://github.com/AVGCFan1995',
      followers_url: 'https://api.github.com/users/AVGCFan1995/followers',
      following_url: 'https://api.github.com/users/AVGCFan1995/following{/other_user}',
      gists_url: 'https://api.github.com/users/AVGCFan1995/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/AVGCFan1995/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/AVGCFan1995/subscriptions',
      organizations_url: 'https://api.github.com/users/AVGCFan1995/orgs',
      repos_url: 'https://api.github.com/users/AVGCFan1995/repos',
      events_url: 'https://api.github.com/users/AVGCFan1995/events{/privacy}',
      received_events_url: 'https://api.github.com/users/AVGCFan1995/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694138665,
        node_id: 'MDU6TGFiZWwxNjk0MTM4NjY1',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/KR',
        name: 'KR',
        color: '4fd19f',
        default: false,
        description: 'South Korea'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-01T14:29:58Z',
    updated_at: '2023-09-07T19:13:30Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: "### Broken Link\r\n\r\nhttps://tistory3.daumcdn.net/tistory/2864460/skin/images/Public_8.m3u8\r\n\r\n### What happened to the stream?\r\n\r\nNot loading\r\n\r\n### Possible Replacement (optional)\r\n\r\n_No response_\r\n\r\n### Notes (optional)\r\n\r\nHey guys, I found this link on https://github.com/iptv-org/iptv/blob/master/streams/kr.m3u is either working or not working when I'm using an UrbanVPN in order to switch it to South Korea when I'm using VLC media player despite my South Korean friend claims this link is working probably it was encrypted or unencrypted.\r\n\r\n### Please confirm the following\r\n\r\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)",
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14108/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14096',
    id: 1874505679,
    node_id: 'I_kwDOCWUK8M5vuq_P',
    number: 14096,
    title: 'Broken: Temple University TV',
    user: {
      login: 'FpFan65',
      id: 85830665,
      node_id: 'MDQ6VXNlcjg1ODMwNjY1',
      avatar_url: 'https://avatars.githubusercontent.com/u/85830665?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/FpFan65',
      html_url: 'https://github.com/FpFan65',
      followers_url: 'https://api.github.com/users/FpFan65/followers',
      following_url: 'https://api.github.com/users/FpFan65/following{/other_user}',
      gists_url: 'https://api.github.com/users/FpFan65/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/FpFan65/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/FpFan65/subscriptions',
      organizations_url: 'https://api.github.com/users/FpFan65/orgs',
      repos_url: 'https://api.github.com/users/FpFan65/repos',
      events_url: 'https://api.github.com/users/FpFan65/events{/privacy}',
      received_events_url: 'https://api.github.com/users/FpFan65/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694118251,
        node_id: 'MDU6TGFiZWwxNjk0MTE4MjUx',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/US',
        name: 'US',
        color: '463faa',
        default: false,
        description: 'United States'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-30T23:16:51Z',
    updated_at: '2023-09-07T00:28:13Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://templeuni.secure.footprint.net/egress/bhandler/templeuni/streama/manifest.m3u8\n\n### What happened to the stream?\n\nOther\n\n### Possible Replacement (optional)\n\nhttps://livestream.telvue.com/templeuni1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8\n\n### Notes (optional)\n\nUpdated Stream\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14096/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14085',
    id: 1871193001,
    node_id: 'I_kwDOCWUK8M5viCOp',
    number: 14085,
    title: 'Broken: KTV 1',
    user: {
      login: 'samimasad',
      id: 781021,
      node_id: 'MDQ6VXNlcjc4MTAyMQ==',
      avatar_url: 'https://avatars.githubusercontent.com/u/781021?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/samimasad',
      html_url: 'https://github.com/samimasad',
      followers_url: 'https://api.github.com/users/samimasad/followers',
      following_url: 'https://api.github.com/users/samimasad/following{/other_user}',
      gists_url: 'https://api.github.com/users/samimasad/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/samimasad/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/samimasad/subscriptions',
      organizations_url: 'https://api.github.com/users/samimasad/orgs',
      repos_url: 'https://api.github.com/users/samimasad/repos',
      events_url: 'https://api.github.com/users/samimasad/events{/privacy}',
      received_events_url: 'https://api.github.com/users/samimasad/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1703945966,
        node_id: 'MDU6TGFiZWwxNzAzOTQ1OTY2',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/KW',
        name: 'KW',
        color: 'e55e7f',
        default: false,
        description: 'Kuwait'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-29T08:51:01Z',
    updated_at: '2023-09-07T00:51:39Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttp://mc-qs.lanesh4d0w.tech/iptv-query?streaming-ip=https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTV1\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nseems all the streams that start with http://mc-qs.lanesh4d0w.tech/iptv-query?streaming-ip do fail , that got to be repalces,\r\nthe source of the TV , for example https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTV1 works fine\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14085/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14063',
    id: 1869737346,
    node_id: 'I_kwDOCWUK8M5vce2C',
    number: 14063,
    title: 'Broken: TV3 Malaysia from my.m3u',
    user: {
      login: 'e0406370',
      id: 79201611,
      node_id: 'MDQ6VXNlcjc5MjAxNjEx',
      avatar_url: 'https://avatars.githubusercontent.com/u/79201611?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/e0406370',
      html_url: 'https://github.com/e0406370',
      followers_url: 'https://api.github.com/users/e0406370/followers',
      following_url: 'https://api.github.com/users/e0406370/following{/other_user}',
      gists_url: 'https://api.github.com/users/e0406370/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/e0406370/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/e0406370/subscriptions',
      organizations_url: 'https://api.github.com/users/e0406370/orgs',
      repos_url: 'https://api.github.com/users/e0406370/repos',
      events_url: 'https://api.github.com/users/e0406370/events{/privacy}',
      received_events_url: 'https://api.github.com/users/e0406370/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 1912922147,
        node_id: 'MDU6TGFiZWwxOTEyOTIyMTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/MY',
        name: 'MY',
        color: 'ea59cf',
        default: false,
        description: 'Malaysia'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2023-08-28T13:10:07Z',
    updated_at: '2023-09-07T00:31:42Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\r\n\r\nhttps://live-sg1.global.ssl.fastly.net/live-hls/tonton1.m3u8\r\n\r\n### What happened to the stream?\r\n\r\nNot loading\r\n\r\n### Possible Replacement (optional)\r\n\r\nhttps://www.livetvmalaysia.online/2019/04/tv3.html\r\n\r\n### Notes (optional)\r\n\r\nUnable to access the TV3 stream through iptv player android app, while other links such as TV1 and TV2 in the m3u8 file are functioning correctly.\r\nAny guidance or support provided would be greatly appreciated.\r\n\r\n### Please confirm the following\r\n\r\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14063/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14044',
    id: 1866840798,
    node_id: 'I_kwDOCWUK8M5vRbre',
    number: 14044,
    title: 'Broken: Tolo TV',
    user: {
      login: 'sunyuanzhe',
      id: 142400045,
      node_id: 'U_kgDOCHzaLQ',
      avatar_url: 'https://avatars.githubusercontent.com/u/142400045?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/sunyuanzhe',
      html_url: 'https://github.com/sunyuanzhe',
      followers_url: 'https://api.github.com/users/sunyuanzhe/followers',
      following_url: 'https://api.github.com/users/sunyuanzhe/following{/other_user}',
      gists_url: 'https://api.github.com/users/sunyuanzhe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sunyuanzhe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sunyuanzhe/subscriptions',
      organizations_url: 'https://api.github.com/users/sunyuanzhe/orgs',
      repos_url: 'https://api.github.com/users/sunyuanzhe/repos',
      events_url: 'https://api.github.com/users/sunyuanzhe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sunyuanzhe/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5367626646,
        node_id: 'LA_kwDOCWUK8M8AAAABP-97lg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/AF',
        name: 'AF',
        color: '996569',
        default: false,
        description: 'Afghanistan'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-25T11:04:56Z',
    updated_at: '2023-09-07T00:34:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://raw.githubusercontent.com/taodicakhia/IPTV_Exception/master/channels/af/tolotv.m3u8\n\n### What happened to the stream?\n\nDisplays a message asking to renew subscription\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nAccess is Forbidden\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14044/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14043',
    id: 1866839527,
    node_id: 'I_kwDOCWUK8M5vRbXn',
    number: 14043,
    title: 'Broken: Lemar TV',
    user: {
      login: 'sunyuanzhe',
      id: 142400045,
      node_id: 'U_kgDOCHzaLQ',
      avatar_url: 'https://avatars.githubusercontent.com/u/142400045?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/sunyuanzhe',
      html_url: 'https://github.com/sunyuanzhe',
      followers_url: 'https://api.github.com/users/sunyuanzhe/followers',
      following_url: 'https://api.github.com/users/sunyuanzhe/following{/other_user}',
      gists_url: 'https://api.github.com/users/sunyuanzhe/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sunyuanzhe/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sunyuanzhe/subscriptions',
      organizations_url: 'https://api.github.com/users/sunyuanzhe/orgs',
      repos_url: 'https://api.github.com/users/sunyuanzhe/repos',
      events_url: 'https://api.github.com/users/sunyuanzhe/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sunyuanzhe/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5367626646,
        node_id: 'LA_kwDOCWUK8M8AAAABP-97lg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/AF',
        name: 'AF',
        color: '996569',
        default: false,
        description: 'Afghanistan'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-25T11:04:01Z',
    updated_at: '2023-09-07T00:34:29Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://raw.githubusercontent.com/taodicakhia/IPTV_Exception/master/channels/af/lemartv.m3u8\n\n### What happened to the stream?\n\nDisplays a message asking to renew subscription\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nAccess is Forbidden\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14043/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14041',
    id: 1866418070,
    node_id: 'I_kwDOCWUK8M5vP0eW',
    number: 14041,
    title: 'Broken: PBS Tucson AZ (KUAT)',
    user: {
      login: 'OmarLopez18',
      id: 14249252,
      node_id: 'MDQ6VXNlcjE0MjQ5MjUy',
      avatar_url: 'https://avatars.githubusercontent.com/u/14249252?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/OmarLopez18',
      html_url: 'https://github.com/OmarLopez18',
      followers_url: 'https://api.github.com/users/OmarLopez18/followers',
      following_url: 'https://api.github.com/users/OmarLopez18/following{/other_user}',
      gists_url: 'https://api.github.com/users/OmarLopez18/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/OmarLopez18/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/OmarLopez18/subscriptions',
      organizations_url: 'https://api.github.com/users/OmarLopez18/orgs',
      repos_url: 'https://api.github.com/users/OmarLopez18/repos',
      events_url: 'https://api.github.com/users/OmarLopez18/events{/privacy}',
      received_events_url: 'https://api.github.com/users/OmarLopez18/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694118251,
        node_id: 'MDU6TGFiZWwxNjk0MTE4MjUx',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/US',
        name: 'US',
        color: '463faa',
        default: false,
        description: 'United States'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-25T06:38:27Z',
    updated_at: '2023-09-07T00:35:06Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://kuatdt.lls.pbs.org/out/v1/8d95fb8559594a7b9359077ea0a512c3/index.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\n_No response_\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14041/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14040',
    id: 1866416765,
    node_id: 'I_kwDOCWUK8M5vP0J9',
    number: 14040,
    title: 'Broken: PBS Phoenix AZ (KAET)',
    user: {
      login: 'OmarLopez18',
      id: 14249252,
      node_id: 'MDQ6VXNlcjE0MjQ5MjUy',
      avatar_url: 'https://avatars.githubusercontent.com/u/14249252?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/OmarLopez18',
      html_url: 'https://github.com/OmarLopez18',
      followers_url: 'https://api.github.com/users/OmarLopez18/followers',
      following_url: 'https://api.github.com/users/OmarLopez18/following{/other_user}',
      gists_url: 'https://api.github.com/users/OmarLopez18/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/OmarLopez18/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/OmarLopez18/subscriptions',
      organizations_url: 'https://api.github.com/users/OmarLopez18/orgs',
      repos_url: 'https://api.github.com/users/OmarLopez18/repos',
      events_url: 'https://api.github.com/users/OmarLopez18/events{/privacy}',
      received_events_url: 'https://api.github.com/users/OmarLopez18/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694118251,
        node_id: 'MDU6TGFiZWwxNjk0MTE4MjUx',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/US',
        name: 'US',
        color: '463faa',
        default: false,
        description: 'United States'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2023-08-25T06:37:33Z',
    updated_at: '2023-09-07T00:35:34Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://kaetdt.lls.pbs.org/out/v1/259f25e61b3d47ce8a7e2339a00c5561/index.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\n_No response_\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14040/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14017',
    id: 1860427275,
    node_id: 'I_kwDOCWUK8M5u494L',
    number: 14017,
    title: 'Broken: Lego Channel',
    user: {
      login: 'baliebox4916',
      id: 28187097,
      node_id: 'MDQ6VXNlcjI4MTg3MDk3',
      avatar_url: 'https://avatars.githubusercontent.com/u/28187097?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/baliebox4916',
      html_url: 'https://github.com/baliebox4916',
      followers_url: 'https://api.github.com/users/baliebox4916/followers',
      following_url: 'https://api.github.com/users/baliebox4916/following{/other_user}',
      gists_url: 'https://api.github.com/users/baliebox4916/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/baliebox4916/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/baliebox4916/subscriptions',
      organizations_url: 'https://api.github.com/users/baliebox4916/orgs',
      repos_url: 'https://api.github.com/users/baliebox4916/repos',
      events_url: 'https://api.github.com/users/baliebox4916/events{/privacy}',
      received_events_url: 'https://api.github.com/users/baliebox4916/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694118251,
        node_id: 'MDU6TGFiZWwxNjk0MTE4MjUx',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/US',
        name: 'US',
        color: '463faa',
        default: false,
        description: 'United States'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-22T02:13:54Z',
    updated_at: '2023-09-07T00:36:14Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://legochannel-roku.amagi.tv/playlist.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nThis Channel Is/Was a Very Good Lego Channel\r\n\r\nBut i Cant Watch it on My PC\r\n\r\n(Tried Progdvb and it said Please Check Network Connection or Try Another Link to Channel)\r\n\r\nTried MyIPTV Player and it said Error Unsupported video type or invalid file path)\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14017/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/13933',
    id: 1854065855,
    node_id: 'I_kwDOCWUK8M5ugsy_',
    number: 13933,
    title: 'Broken: Rai 1',
    user: {
      login: 'm3u-playlists',
      id: 141451187,
      node_id: 'U_kgDOCG5fsw',
      avatar_url: 'https://avatars.githubusercontent.com/u/141451187?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/m3u-playlists',
      html_url: 'https://github.com/m3u-playlists',
      followers_url: 'https://api.github.com/users/m3u-playlists/followers',
      following_url: 'https://api.github.com/users/m3u-playlists/following{/other_user}',
      gists_url: 'https://api.github.com/users/m3u-playlists/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/m3u-playlists/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/m3u-playlists/subscriptions',
      organizations_url: 'https://api.github.com/users/m3u-playlists/orgs',
      repos_url: 'https://api.github.com/users/m3u-playlists/repos',
      events_url: 'https://api.github.com/users/m3u-playlists/events{/privacy}',
      received_events_url: 'https://api.github.com/users/m3u-playlists/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694139293,
        node_id: 'MDU6TGFiZWwxNjk0MTM5Mjkz',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/IT',
        name: 'IT',
        color: 'f254ae',
        default: false,
        description: 'Italy'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-08-17T00:35:23Z',
    updated_at: '2023-09-07T00:39:57Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: "### Broken Link\n\nhttp://ott-cdn.ucom.am/s29/04.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\nit doesn't load\n\n### Please confirm the following\n\n- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)",
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13933/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/13733',
    id: 1837944461,
    node_id: 'I_kwDOCWUK8M5tjM6N',
    number: 13733,
    title: 'Broken: Ary QTV',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694140866,
        node_id: 'MDU6TGFiZWwxNjk0MTQwODY2',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/PK',
        name: 'PK',
        color: '20d68a',
        default: false,
        description: 'Pakistan'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-08-05T21:28:12Z',
    updated_at: '2023-09-07T00:45:08Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://aryqtv.aryzap.com/24591444d352c03d824757bbf5a60d7d/6459fab3/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/main.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\nhttps://aryqtv.aryzap.com/859af40a1493997e1ea86c1054773823/64cfef73/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/ARYQTVH264_720p.m3u8\n\n### Notes (optional)\n\nOriginal request: #13731\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13733/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/13555',
    id: 1807032220,
    node_id: 'I_kwDOCWUK8M5rtR-c',
    number: 13555,
    title: 'Broken: Colors Cineplex',
    user: {
      login: 'uyseeer',
      id: 135757448,
      node_id: 'U_kgDOCBd-iA',
      avatar_url: 'https://avatars.githubusercontent.com/u/135757448?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/uyseeer',
      html_url: 'https://github.com/uyseeer',
      followers_url: 'https://api.github.com/users/uyseeer/followers',
      following_url: 'https://api.github.com/users/uyseeer/following{/other_user}',
      gists_url: 'https://api.github.com/users/uyseeer/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/uyseeer/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/uyseeer/subscriptions',
      organizations_url: 'https://api.github.com/users/uyseeer/orgs',
      repos_url: 'https://api.github.com/users/uyseeer/repos',
      events_url: 'https://api.github.com/users/uyseeer/events{/privacy}',
      received_events_url: 'https://api.github.com/users/uyseeer/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694119113,
        node_id: 'MDU6TGFiZWwxNjk0MTE5MTEz',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/IN',
        name: 'IN',
        color: 'd8139a',
        default: false,
        description: 'India'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-07-17T05:54:19Z',
    updated_at: '2023-09-07T00:45:31Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://prod-sports-north-gm.jiocinema.com/bpk-tv/Colors_Cineplex_voot_MOB/Fallback/index.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\n_No response_\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13555/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/13538',
    id: 1805880578,
    node_id: 'I_kwDOCWUK8M5ro40C',
    number: 13538,
    title: 'Broken: ARY Digital [PK]',
    user: {
      login: 'uyseeer',
      id: 135757448,
      node_id: 'U_kgDOCBd-iA',
      avatar_url: 'https://avatars.githubusercontent.com/u/135757448?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/uyseeer',
      html_url: 'https://github.com/uyseeer',
      followers_url: 'https://api.github.com/users/uyseeer/followers',
      following_url: 'https://api.github.com/users/uyseeer/following{/other_user}',
      gists_url: 'https://api.github.com/users/uyseeer/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/uyseeer/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/uyseeer/subscriptions',
      organizations_url: 'https://api.github.com/users/uyseeer/orgs',
      repos_url: 'https://api.github.com/users/uyseeer/repos',
      events_url: 'https://api.github.com/users/uyseeer/events{/privacy}',
      received_events_url: 'https://api.github.com/users/uyseeer/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694140866,
        node_id: 'MDU6TGFiZWwxNjk0MTQwODY2',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/PK',
        name: 'PK',
        color: '20d68a',
        default: false,
        description: 'Pakistan'
      },
      {
        id: 1707513547,
        node_id: 'MDU6TGFiZWwxNzA3NTEzNTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/broken%20stream',
        name: 'broken stream',
        color: 'FBCA04',
        default: false,
        description: 'Stream is not working properly'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5932506810,
        node_id: 'LA_kwDOCWUK8M8AAAABYZreug',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:remove',
        name: 'streams:remove',
        color: '5373a2',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 3,
    created_at: '2023-07-15T04:36:15Z',
    updated_at: '2023-09-07T00:46:05Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Broken Link\n\nhttps://arydigital.aryzap.com/101647b94a234edb1d8be0996ebedc9e/6459fa3c/v1/0183ea2408f90b8ed5941a38bc72/0183ea24302d0b8ed5941a38bc75/main.m3u8\n\n### What happened to the stream?\n\nNot loading\n\n### Possible Replacement (optional)\n\n_No response_\n\n### Notes (optional)\n\n_No response_\n\n### Please confirm the following\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/13538/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
