module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14179',
    id: 1884926953,
    node_id: 'I_kwDOCWUK8M5wWbPp',
    number: 14179,
    title: 'Add: Manorama News',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694119113,
        node_id: 'MDU6TGFiZWwxNjk0MTE5MTEz',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/IN',
        name: 'IN',
        color: 'd8139a',
        default: false,
        description: 'India'
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:add',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-07T00:38:55Z',
    updated_at: '2023-09-07T00:48:32Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Channel ID\n\nManoramaNews.in\n\n### Stream URL\n\nhttps://ythls.onrender.com/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8\n\n### Label\n\nNot 24/7\n\n### Notes (optional)\n\nSource: https://github.com/iptv-org/iptv/issues/14007#issuecomment-1686942043\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14179/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14178',
    id: 1884922249,
    node_id: 'I_kwDOCWUK8M5wWaGJ',
    number: 14178,
    title: 'Add: TV3',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1912922147,
        node_id: 'MDU6TGFiZWwxOTEyOTIyMTQ3',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/MY',
        name: 'MY',
        color: 'ea59cf',
        default: false,
        description: 'Malaysia'
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:add',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-07T00:30:51Z',
    updated_at: '2023-09-07T00:48:23Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Channel ID\n\nTV3.my\n\n### Stream URL\n\nhttps://live-streams-ssai-01.tonton.com.my/live/2dd2b7cd-1b34-4871-b669-57b5c9beca23/live.isml/.m3u8\n\n### Label\n\nNone\n\n### Notes (optional)\n\nSource: https://github.com/iptv-org/iptv/issues/14063#issuecomment-1695783106\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14178/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14177',
    id: 1884920274,
    node_id: 'I_kwDOCWUK8M5wWZnS',
    number: 14177,
    title: 'Add: Temple University TV',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694118251,
        node_id: 'MDU6TGFiZWwxNjk0MTE4MjUx',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/US',
        name: 'US',
        color: '463faa',
        default: false,
        description: 'United States'
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:add',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-07T00:27:51Z',
    updated_at: '2023-09-07T00:47:15Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Channel ID\n\nTUTV.us\n\n### Stream URL\n\nhttps://livestream.telvue.com/templeuni1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8\n\n### Label\n\nNone\n\n### Notes (optional)\n\nSource: https://github.com/iptv-org/iptv/issues/14096#issue-1874505679\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14177/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14176',
    id: 1884926953,
    node_id: 'I_kwDOCWUK8M5wWbPp',
    number: 14176,
    title: 'Add: Manorama News',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694119113,
        node_id: 'MDU6TGFiZWwxNjk0MTE5MTEz',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/IN',
        name: 'IN',
        color: 'd8139a',
        default: false,
        description: 'India'
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:add',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-09-07T00:38:55Z',
    updated_at: '2023-09-07T00:48:32Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Channel ID\n\nManoramaNews.in\n\n### Stream URL\n\nhttps://ythls.onrender.com/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8\n\n### Label\n\nNot 24/7\n\n### Notes (optional)\n\nSource: https://github.com/iptv-org/iptv/issues/14007#issuecomment-1686942043\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14176/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14175',
    id: 1884859778,
    node_id: 'I_kwDOCWUK8M5wWK2C',
    number: 14175,
    title: 'Add: TFX',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 1694117286,
        node_id: 'MDU6TGFiZWwxNjk0MTE3Mjg2',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/FR',
        name: 'FR',
        color: 'f7ec1b',
        default: false,
        description: 'France'
      },
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:add',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-06T22:54:25Z',
    updated_at: '2023-09-07T00:57:11Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Channel ID\n\nTFX.fr\n\n### Stream URL\n\nhttp://livetv.ktv.zone/13/play.m3u8\n\n### Label\n\nNone\n\n### Notes (optional)\n\nSource: https://github.com/iptv-org/iptv-org.github.io/issues/1381\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14175/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
