module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110',
    repository_url: 'https://api.github.com/repos/iptv-org/iptv',
    labels_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110/comments',
    events_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110/events',
    html_url: 'https://github.com/iptv-org/iptv/issues/14110',
    id: 1884922249,
    node_id: 'I_kwDOCWUK8M5wWaGJ',
    number: 14110,
    title: 'Edit: Tele2000',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5923498886,
        node_id: 'LA_kwDOCWUK8M8AAAABYRFrhg',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/approved',
        name: 'approved',
        color: '85ddde',
        default: false,
        description: ''
      },
      {
        id: 5923508587,
        node_id: 'LA_kwDOCWUK8M8AAAABYRGRaw',
        url: 'https://api.github.com/repos/iptv-org/iptv/labels/streams:add',
        name: 'streams:edit',
        color: '017ff9',
        default: false,
        description: 'Request to add a new link to a playlist'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-07T00:30:51Z',
    updated_at: '2023-09-07T00:48:23Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Stream URL\n\nhttps://servilive.com:3126/live/tele2000live.m3u8\n\n### Channel ID\n\nBBCAmericaEast.us\n\n### Channel Name\n\nBBC America\n\n### Quality\n\n720p\n\n### Label\n\nGeo-blocked\n\n### HTTP User-Agent\n\nMozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246\n\n### HTTP Referrer\n\n_No response_\n\n### Notes\n\n_No response_\n\n### Contributing Guide\n\n- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/iptv/issues/14110/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
