name: 🛠 Broken Stream
description: Report a broken stream
title: "Fix: "
labels: [ "broken stream" ]

body:
  - type: markdown
    attributes:
      value: |
         Please fill out the issue template as much as you can so we could efficiently process your request
         **IMPORTANT**: An issue may contain a request for only one channel, otherwise it will be closed
         
         Channels present in this repository come from variety of sources, some may have overbalanced load at times, temporal issues or just be far away from your location to play smoothly.
         Please wait for a few hours at least before filling this form.
         
  - type: checkboxes
    id: preliminary
    attributes:
     label: I have verified that
     options:
      - label: I use the GitHub playlist link and not a downloaded/cached version of the file
        required: true
      - label: My TV player has updated this playlist after 0:00 GMT and is set to update it daily
        required: true
      - label: I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days 
        required: true
        
  - type: input
    id: name
    attributes:
      label: Channel Name
      description: Full name of the channel. Please use the exact name, as in how it appears in the playlist.
      placeholder: 'Fox Life Russia'
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: What happened to the stream?
      options:
        - It is now offline (disappeared from the playlist)
        - It is stuck at a single frame/the same segment
        - I see visual artifacts
        - It is buffering to unplayable point
    validations:
      required: true
      
  - type: input
    id: playlist
    attributes:
      label: Playlist
      description: What playlist was used to get the channel from?
      placeholder: 'ex. https://iptv-org.github.io/iptv/countries/au.m3u'
    validations:
      required: true
      
  - type: input
    id: link
    attributes:
      label: Broken Link
      description: Please specify the broken link from a playlist if you can
      placeholder: 'ex. https://lnc-kdfw-fox-aws.tubi.video/index.m3u8'
      
  - type: input
    id: alt
    attributes:
      label: Possible Replacement
      description: If you know an alternate non-protected source or the way to fix current stream please let us know 
      placeholder: 'ex. https://lnc-kdfw-fox-aws.tubi.video/index.m3u8'
      
  - type: input
    id: notes
    attributes:
      label: Notes
      placeholder: 'Anything else we should know?'
