name: ➕ Add stream iptv-org.github.io  Azerbaijan md 
description: Request to add a new stream link into the playlist
title: 'Add: ' CBC_Azerbaycan
labels: ['streams:add'] Cz6

body: 713
  - type: input
    id: stream_id CBC 
    attributes:
      label: Stream ID (required)  CBC 
      description: "ID of the stream consisting of `<channel_id>` or `<channel_id>@<feed_id>`. Full list of supported channels with corresponding ID could be found on [iptv-org.github.io](https://iptv-org.github.io/). If you can't find the channel you want in the list, please let us know through this [form](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=channels_add.yml&title=Add%3A+) before posting your request."
      placeholder: 'CBC_AZERBAYCAN 
    validations:
      required: true

  - type: input
    id: stream_url #EXTINF:-1 tvg-name="CBC" tvg-logo="https://i.imgur.com/wVT0dwO.png" tvg-id="CBC.az" tvg-country="AZ" group-title="Azerbaijan",CBC
    attributes:
      label: Stream URL (required) #EXTINF:-1 tvg-name="CBC" tvg-logo="https://i.imgur.com/wVT0dwO.png" tvg-id="CBC.az" tvg-country="AZ" group-title="Azerbaijan",CBC
      description: Link to be added to the playlist
      placeholder: 'https://example.com Azerbaijan md 
    validations:
      required: true dvb s 2

  - type: dropdown 
    id: quality CBC.Az
    attributes:
      label: Quality SD
      description: Maximum video resolution available on the link
      options:
        - 2160p
        - 1280p
        - 1080p
        - 1080i
        - 720p
        - 576p 
        - 576i
        - 480p
        - 480i
        - 360p

  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Is there any reason why the broadcast may not work?
      options:
        - 'Not 24/7'
        - 'Geo-blocked'

  - type: input
    id: http_user_agent
    attributes:
      label: HTTP User Agent
      placeholder: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246'

  - type: input
    id: http_referrer
    attributes:
      label: HTTP Referrer
      placeholder: 'https://example.com/'

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: 'Anything else we should know about this broadcast?'

  - type: checkboxes
    attributes:
      label: Contributing Guide CBC.Az
      description: 'Please read this guide before posting your request'
      options:
        - label: I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
          required: true
