name: ✏️ Edit stream
description: Request to edit stream description
title: 'Edit: '
labels: ['streams:edit']

body:
  - type: input
    id: stream_url
    attributes:
      label: Stream URL (required)
      description: Link to the stream to be updated
      placeholder: 'https://lnc-kdfw-fox-aws.tubi.video/index.m3u8'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        What exactly needs to be changed? To delete an existing value without replacement use the `~` symbol.

  - type: input
    id: new_stream_url
    attributes:
      label: New Stream URL
      description: New link to the stream
      placeholder: 'https://servilive.com:3126/live/tele2000live.m3u8'

  - type: input
    id: stream_id
    attributes:
      label: Stream ID
      description: "ID of the stream consisting of `<channel_id>` or `<channel_id>@<feed_id>`. Full list of supported channels with corresponding ID could be found on [iptv-org.github.io](https://iptv-org.github.io/). If you can't find the channel you want in the list, please let us know through this [form](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=channels_add.yml&title=Add%3A+) before posting your request."
      placeholder: 'BBCAmerica.us@East'

  - type: dropdown
    id: quality
    attributes:
      label: Quality
      description: Maximum video resolution available on the link
      options:
        - 2160p
        - 1280p
        - 1080p
        - 1080i
        - 720p
        - 576p
        - 576i
        - 480p
        - 480i
        - 360p
        - '~'

  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Is there any reason why the broadcast may not work?
      options:
        - 'Not 24/7'
        - 'Geo-blocked'
        - '~'

  - type: input
    id: http_user_agent
    attributes:
      label: HTTP User Agent
      placeholder: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246'

  - type: input
    id: http_referrer
    attributes:
      label: HTTP Referrer
      placeholder: 'https://example.com/'

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: 'Anything else we should know?'

  - type: checkboxes
    attributes:
      label: Contributing Guide
      description: 'Please read this guide before posting your request'
      options:
        - label: I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
          required: true
